entrypoints:
    'enhavo/media/image-cropper':
        path: '../Entrypoint/image-cropper.ts'
        build: enhavo
    'enhavo/media/media-library':
        path: '../Entrypoint/media-library.ts'
        build: enhavo
services:
    '@enhavo/media/Loader/MediaLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/View/View'
            - '@enhavo/core/Router'
        tags:
            - 'enhavo_app.form'

    '@enhavo/media/MediaLibrary/MediaLibraryApp':
        chunk: 'media'
        arguments:
            - '@enhavo/app/View/View'
            - '@enhavo/app/Action/ActionManager'
            - '@enhavo/media/MediaLibrary/MediaLibrary'
            - '@enhavo/app/FlashMessage/FlashMessenger'

    '@enhavo/media/MediaLibrary/MediaLibrary':
        chunk: 'media'
        arguments:
            - 'param:data.media'
            - '@enhavo/core/Router'
            - '@enhavo/app/ViewStack/EventDispatcher'
            - '@enhavo/app/View/View'
            - '@enhavo/core/Translator'
            - '@enhavo/app/Vue/VueRegistry'

    '@enhavo/media/MediaLibrary/Components/ApplicationComponent.vue':
        chunk: 'media'
        static: true

    '@enhavo/media/MediaLibrary/Components/MediaLibraryComponent.vue':
        chunk: 'media'
        static: true
        tags:
            - { name: vue.component, component: 'media-library' }

    '@enhavo/media/ImageCropper/ImageCropperApp':
        chunk: 'image-cropper'
        arguments:
            - 'param:data.format'
            - '@enhavo/app/ViewStack/EventDispatcher'
            - '@enhavo/app/View/View'
            - '@enhavo/app/Action/ActionManager'
            - '@enhavo/app/FlashMessage/FlashMessenger'
            - '@enhavo/app/Vue/VueRegistry'

    '@enhavo/media/ImageCropper/Components/ImageCropperComponent.vue':
        chunk: 'image-cropper'
        static: true

    '@enhavo/media/ImageCropper/Components/ImageCropperStageComponent.vue':
        chunk: 'vue'
        static: true
        tags:
            - { name: vue.component, component: 'image-cropper' }